// Generated by https://quicktype.io

export interface Clasificacion {
  id:            number;
  referencia:    string;
  consecutivo:   number;
  codcolor:      string | null;
  producto:      string;
  tiquete:       number;
  codbar:        string;
  descgrupo:     string;
  grupo:         string;
  coleccion:     string;
  subgrupo:      string;
  descsubgrupo:  string;
  diseno:        string | null;
  concepto:      string;
  composicion:   string;
  clasificacion: string | null;
}
