// Generated by https://quicktype.io

export interface Clasificacion {
  id:            number;
  producto:      string;
  tiquete:       number;
  codbar:        string;
  descgrupo:     string;
  grupo:         string;
  coleccion:     string;
  subgrupo:      string;
  descsubgrupo:  string;
  diseno:        string;
  concepto:      string;
  composicion:   string;
  clasificacion: string;
}
